# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a2a7812cd2a0896f5a0098f12edf009edd0850a4347f4ed316e401799ac725e9a446de3efd5483930cff883f0d1cc323369ae4860735db167540b14de73c2d0

test:
  secret_key_base: 0131f0f5e7a8df3f43d2d8207e9870373244878d62ad431fa6aee3b9f6306f317e09d12cd299d7eadc6959974a2fb0a5b7046222192d11c557774ae22704394f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
